# Generated by Django 5.0.6 on 2024-07-01 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_title', models.CharField(max_length=180, null=True)),
                ('batch_starting_time', models.TimeField(null=True)),
                ('batch_ending_time', models.TimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='to_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.classhave'),
        ),
        migrations.AddField(
            model_name='students',
            name='batch',
            field=models.ForeignKey(max_length=180, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.batch'),
        ),
        migrations.CreateModel(
            name='Departandhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(max_length=180, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('headname', models.ForeignKey(max_length=180, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
            ],
        ),
    ]
