# Generated by Django 5.0.6 on 2024-07-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_batch_students_to_class_students_batch_departandhead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='father',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='father_occupation',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='first_name',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_name',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='mother',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='mother_occupation',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='password',
            field=models.CharField(max_length=180, null=True),
        ),
    ]
