# Generated by Django 5.0.6 on 2024-07-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_students_dob_alter_students_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='joined_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
