# Generated by Django 5.0.6 on 2024-07-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_to_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_msg',
            name='to_student',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='to_msg',
            name='to_teacher',
            field=models.BinaryField(null=True),
        ),
    ]
