# Generated by Django 5.0.6 on 2024-07-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_to_msg_to_student_alter_to_msg_to_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_msg',
            name='to_student',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='to_msg',
            name='to_teacher',
            field=models.BooleanField(null=True),
        ),
    ]
