# Generated by Django 5.0.6 on 2024-07-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_to_msg_to_student_alter_to_msg_to_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_msg',
            name='sent_by',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='to_msg',
            name='to_admin',
            field=models.BooleanField(null=True),
        ),
    ]
