# Generated by Django 5.0.6 on 2024-07-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_to_msg_sent_by_to_msg_to_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_msg',
            name='user_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
