# Generated by Django 5.0.6 on 2024-07-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='classlink',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
